// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coordinator.proto

package grpcserver;

public final class Coordinator {
  private Coordinator() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021coordinator.proto\"7\n\021UpdateTaskRequest" +
      "\022\016\n\006taskId\030\001 \001(\004\022\022\n\ntaskStatus\030\002 \001(\t\"F\n\022" +
      "UpdateTaskResponse\022\016\n\006taskId\030\001 \001(\004\022\017\n\007me" +
      "ssage\030\002 \001(\t\022\017\n\007success\030\003 \001(\010\"$\n\020HeartBea" +
      "tRequest\022\020\n\010workerId\030\001 \001(\004\"(\n\021HeartBeatR" +
      "esponse\022\023\n\013acknowledge\030\001 \001(\0102\203\001\n\022Coordin" +
      "atorService\0225\n\nupdateTask\022\022.UpdateTaskRe" +
      "quest\032\023.UpdateTaskResponse\0226\n\rsendHeartB" +
      "eat\022\021.HeartBeatRequest\032\022.HeartBeatRespon" +
      "seB\016\n\ngrpcserverP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UpdateTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UpdateTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateTaskRequest_descriptor,
        new java.lang.String[] { "TaskId", "TaskStatus", });
    internal_static_UpdateTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UpdateTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateTaskResponse_descriptor,
        new java.lang.String[] { "TaskId", "Message", "Success", });
    internal_static_HeartBeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HeartBeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatRequest_descriptor,
        new java.lang.String[] { "WorkerId", });
    internal_static_HeartBeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_HeartBeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatResponse_descriptor,
        new java.lang.String[] { "Acknowledge", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
