// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coordinator.proto

package grpcserver;

public interface HeartBeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartBeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 workerId = 1;</code>
   * @return The workerId.
   */
  long getWorkerId();
}
