// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coordinator.proto

package grpcserver;

public interface UpdateTaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateTaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 taskId = 1;</code>
   * @return The taskId.
   */
  long getTaskId();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>bool success = 3;</code>
   * @return The success.
   */
  boolean getSuccess();
}
