// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coordinator.proto

package grpc;

public interface HeartBeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartBeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 workerId = 1;</code>
   * @return The workerId.
   */
  long getWorkerId();

  /**
   * <code>string hostname = 2;</code>
   * @return The hostname.
   */
  java.lang.String getHostname();
  /**
   * <code>string hostname = 2;</code>
   * @return The bytes for hostname.
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>string port = 3;</code>
   * @return The port.
   */
  java.lang.String getPort();
  /**
   * <code>string port = 3;</code>
   * @return The bytes for port.
   */
  com.google.protobuf.ByteString
      getPortBytes();
}
