// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coordinator.proto

package grpc;

public interface TaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 taskId = 1;</code>
   * @return The taskId.
   */
  long getTaskId();

  /**
   * <code>string data = 2;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
