// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coordinator.proto

package grpc;

public interface UpdateTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 taskId = 1;</code>
   * @return The taskId.
   */
  long getTaskId();

  /**
   * <code>string taskStatus = 2;</code>
   * @return The taskStatus.
   */
  java.lang.String getTaskStatus();
  /**
   * <code>string taskStatus = 2;</code>
   * @return The bytes for taskStatus.
   */
  com.google.protobuf.ByteString
      getTaskStatusBytes();
}
