// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: taskmanager.proto

package grpc;

public interface HeartBeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartBeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool acknowledge = 1;</code>
   * @return The acknowledge.
   */
  boolean getAcknowledge();
}
