// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: taskmanager.proto

package grpc;

public interface UpdateTaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateTaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string taskId = 1;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string taskId = 1;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>bool acknowledge = 2;</code>
   * @return The acknowledge.
   */
  boolean getAcknowledge();
}
