services:
  mongoDB:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: scheduler
