// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: taskmanager.proto

package grpc;

public final class Taskmanager {
  private Taskmanager() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021taskmanager.proto\"+\n\013TaskRequest\022\016\n\006ta" +
      "skId\030\001 \001(\t\022\014\n\004data\030\002 \001(\t\";\n\014TaskResponse" +
      "\022\016\n\006taskId\030\001 \001(\t\022\033\n\006status\030\002 \001(\0162\013.TaskS" +
      "tatus\"D\n\021UpdateTaskRequest\022\016\n\006taskId\030\001 \001" +
      "(\t\022\037\n\ntaskStatus\030\002 \001(\0162\013.TaskStatus\"9\n\022U" +
      "pdateTaskResponse\022\016\n\006taskId\030\001 \001(\t\022\023\n\013ack" +
      "nowledge\030\002 \001(\010\"D\n\020HeartBeatRequest\022\020\n\010wo" +
      "rkerId\030\001 \001(\004\022\020\n\010hostname\030\002 \001(\t\022\014\n\004port\030\003" +
      " \001(\t\"(\n\021HeartBeatResponse\022\023\n\013acknowledge" +
      "\030\001 \001(\010*@\n\nTaskStatus\022\013\n\007PENDING\020\000\022\r\n\tCOM" +
      "PLETED\020\001\022\n\n\006QUEUED\020\002\022\n\n\006FAILED\020\0032\203\001\n\022Tas" +
      "kManagerService\0225\n\nupdateTask\022\022.UpdateTa" +
      "skRequest\032\023.UpdateTaskResponse\0226\n\rsendHe" +
      "artBeat\022\021.HeartBeatRequest\032\022.HeartBeatRe" +
      "sponse28\n\rWorkerService\022\'\n\010sendTask\022\014.Ta" +
      "skRequest\032\r.TaskResponseB\010\n\004grpcP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TaskRequest_descriptor,
        new java.lang.String[] { "TaskId", "Data", });
    internal_static_TaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TaskResponse_descriptor,
        new java.lang.String[] { "TaskId", "Status", });
    internal_static_UpdateTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UpdateTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateTaskRequest_descriptor,
        new java.lang.String[] { "TaskId", "TaskStatus", });
    internal_static_UpdateTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UpdateTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateTaskResponse_descriptor,
        new java.lang.String[] { "TaskId", "Acknowledge", });
    internal_static_HeartBeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_HeartBeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatRequest_descriptor,
        new java.lang.String[] { "WorkerId", "Hostname", "Port", });
    internal_static_HeartBeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_HeartBeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatResponse_descriptor,
        new java.lang.String[] { "Acknowledge", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
